# IMPORTANT REFERENCE: https://www.youtube.com/watch?v=uimdXPZc40I&list=PLkrJrLs7xfbXcEKhTCKRSr2VXH4yiBeXo&index=4
project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!DAY1_NOTEBOOK_UPDATE_PLAN.md"
    - "!CLAUDE_MD_PLAN.md"


website:
  title: "MGMT 47400: Predictive Analytics (Summer 2026 - 4-Week Intensive)"
  sidebar:
    background: primary
    logo: "images/mgmt_474_ai_logo_02-modified.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/davi-moreira/2026Summer_predictive_analytics_purdue_MGMT474
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule and Material

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
editor: visual

